### PR TITLE
feature/add_few_missing_country_details

### PR DESCRIPTION
**Pull request by shantanu-deriv**
Add information on countries below as they are missing from `locale.sql`
- ax
- sx
- ss
- mf
- cw

### CODE REVIEW

**Comment by shantanu-deriv** [comment]
@castaway can you please have a look at this PR and merge. We use this library and found out some locales were missing.

**Comment by shantanu-deriv** [comment]
@castaway any ETA on when this can be merged?

**Comment by castaway** [comment]
Oops sorry, will put on my list for coming weekend.

**Comment by castaway** [comment]
Sorry that took ages! I've released it as 0.82 (along with all the other bits in the dev release)

**Comment by shantanu-deriv** [comment]
Thanks!

**Pull request merged**
